apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-api
  namespace: key-vault-demo
  labels:
    app: sb-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sb-api
  template:
    metadata:
      labels:
        app: sb-api
    spec:
      serviceAccountName: key-vault-demo-sa
      automountServiceAccountToken: true
      containers:
      - name: sb-api
        image: ghcr.io/jorturfer/netcoreconf-2022-bnc:main
        ports:
        - containerPort: 80
        env:
        - name: KEYVAULTNAME
          value: kv-netcoreconf
        - name: SERVICEBUS__QUEUE
          value: key-vault
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sb-api-service
  namespace: key-vault-demo
spec:
  selector:
    app: sb-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80