apiVersion: v1
kind: Secret
metadata:
  name: sb-api-secret
  namespace: secrets-demo
type: Opaque
stringData:
  SERVICEBUS__CONNECTION: "ServiceBus Connection"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-api
  namespace: secrets-demo
  labels:
    app: sb-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sb-api
  template:
    metadata:
      labels:
        app: sb-api
    spec:
      containers:
      - name: sb-api
        image: ghcr.io/jorturfer/netcoreconf-2022-bnc:main
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: sb-api-secret
        env:
        - name: SERVICEBUS__QUEUE
          value: secrets
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sb-api-service
  namespace: secrets-demo
spec:
  selector:
    app: sb-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80